name: WebBuild Digital Ocean Installer
image: ubuntu-16-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: webbuild
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
  runcmd:
    - cd /home/webbuild && git clone git://github.com/jaskipper/webbuild-setup.git && cd webbuild-setup && bash webbuild
