#!/bin/bash

#Get Current run directory directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXPORT DIR

#Getting .env variables
echo "Setting variables from wb.conf file"
echo ""
set -o allexport
source $DIR/wb.conf

DEBIAN_FRONTEND=noninteractive apt
apt --yes update
apt --yes install unzip jq

#Get MySQL Root Password and put it in a variable
rootdbpassword=$(grep root_mysql /root/.digitalocean_password | sed 's#"##g' | sed 's#root_mysql_pass=##g')

echo "Removing Root MySQL Configuration file"
if [ -f /root/.my.cnf ]; then
  rm /root/.my.cnf
fi

echo "Creating New Root MySQL Configuration file"
echo "[client]" >> /root/.my.cnf
echo "user=root" >> /root/.my.cnf
echo "password=$rootdbpassword" >> /root/.my.cnf

echo "Changing Permissions on Root MySQL Configuration file"
chmod 600 /root/.my.cnf

echo "Wordpress Plugins & Themes Setup"
echo ""

# Adding an autoupdater to .bashrc
if ! grep -q "wbupdate" /root/.bashrc; then
  echo "function wbupdate {
    rm -R ~/webbuild-setup
    git clone https://github.com/jaskipper/webbuild-setup.git
  }
  function pluginsupdate {
    /root/webbuild-setup/install-files/skipperplugins
  }" >> /root/.bashrc
  source .bashrc
fi



# Setting correct server Timezone
echo -e "Updating Server Time Zone"
timedatectl set-timezone $TIMEZONE

$DIR/install-files/wordpress
echo "Installing Essential Wordpress Plugins"
$DIR/install-files/skipperplugins
$DIR/install-files/mpplugins

if [ $CHURCHCRM_INSTALL = "yes" ];
then
  echo "Installing ChurchCRM"
  $DIR/install-files/churchcrm
fi #End ChurchCRM

if [ $OWNCLOUD_INSTALL = "yes" ]
then
  echo "Installing OwnCloud"
  $DIR/install-files/owncloud
fi

if [ $SSL_INSTALL = "yes" ];
then
  echo "Installing SSL"
  $DIR/install-files/sslsetup
fi
