#!/bin/bash

#Get Current run directory directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXPORT DIR
#Get MySQL Root Password and put it in a variable
rootdbpassword=$(grep root_mysql /root/.digitalocean_password | sed 's#"##g' | sed 's#root_mysql_pass=##g')

echo "Removing Root MySQL Configuration file"
if [ -f /root/.my.cnf ]; then
  rm /root/.my.cnf
fi

#Getting .env variables
echo "Setting variables from wb.conf file"
echo ""
set -o allexport
source $DIR/wb.conf

DEBIAN_FRONTEND=noninteractive apt
apt --yes update
apt --yes install unzip jq

echo "Wordpress Plugins & Themes Setup"
echo ""

timedatectl set-timezone $TIMEZONE

echo "Creating New Root MySQL Configuration file"
echo "[client]" >> /root/.my.cnf
echo "user=root" >> /root/.my.cnf
echo "password=$rootdbpassword" >> /root/.my.cnf

echo "Changing Permissions on Root MySQL Configuration file"
chmod 600 /root/.my.cnf

$DIR/install-files/wordpress
echo "Installing Essential Wordpress Plugins"
$DIR/install-files/mbplugins

if [ $CHURCHCRM_INSTALL = "yes" ];
then
  echo "Installing ChurchCRM"
  $DIR/install-files/churchcrm
fi #End ChurchCRM

if [ $OWNCLOUD_INSTALL = "yes" ]
then
  echo "Installing OwnCloud"
  $DIR/install-files/owncloud
fi

if [ $SSL_INSTALL = "yes" ];
then
  echo "Installing SSL"
  $DIR/install-files/sslsetup
fi
