#!/bin/bash
echo ""
echo "#   Installing Latest ChurchCRM and Dependencies    #"
echo ""

#Getting .env variables
if [ ! $DOMAIN_NAME ]; then
  PWDIR=${PWD##*/}
  set -o allexport
  if [ $PWDIR == "webbuild-setup" ]; then
    source ./wb.conf
  elif [ $PWDIR == "install-files" ]; then
    source ../wb.conf
  fi
fi

#Download Latest Stable release
if (curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"); then
  echo "Downloaded Successfully!"
  unzip Church*.zip
  rm Church*.zip
  chown -R www-data:www-data churchcrm
  chmod -R 755 churchcrm
  find ./churchcrm/. -type f -exec chmod 644 {} +
  rm -R /var/www/churchcrm
  mv churchcrm /var/www
else
  echo -e "ChurchCRM was \e[31mNOT\e[0m able to Download Successfully. I will go ahead and install all of the nessesary depencencies in order to allow it to run once it is installed successfully. You can try running this script again by changing directories into the 'install-files' directory and running '\e[31m./churchcrm\e[0m' If it continues to fail, you have several other options.

  1) Go to the releases page at ChurchCRM's github account (https://github.com/ChurchCRM/CRM/releases) and get the download link to the latest release (Right click on the latest zip file and 'copy link'). Once this is install process is over, you can enter the following commands.
\e[31m
  cd /var/www
  wget https://github.com/ChurchCRM/CRM/releases/download/2.4.2/ChurchCRM-2.4.2.zip (Or whatever the latest file link is)
  unzip Church*.zip
  chown -R www-data:www-data churchcrm
  chmod -R 755 churchcrm
  find ./churchcrm/. -type f -exec chmod 644 {} +
\e[0m

  2) You can also download the file directly to your computer and upload it through SFTP (Using an FTP Client like Filezilla). You want to make sure that you upload it to the /var/www folder."
fi

PKG_NAME=php7.0-mbstring
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

PKG_NAME=php7.0-mcrypt
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

echo ""
echo "#       Creating ChurchCRM User and Database        #"
echo ""

if (mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $CHURCHCRM_DATABASE;"); then
  echo "Database \"$CHURCHCRM_DATABASE\" created"
else
  echo "There was a problem installing the Database \"$CHURCHCRM_DATABASE\""
fi

if (mysql -uroot -e "CREATE USER IF NOT EXISTS '$CHURCHCRM_DB_USER'@'localhost' IDENTIFIED BY '$CHURCHCRM_DB_PASSWORD';"); then
  echo "User \"$CHURCHCRM_DB_USER\" created @localhost with password \"$CHURCHCRM_DB_PASSWORD\""
else
  echo "There was a problem adding the User \"$CHURCHCRM_DB_USER\""
fi

if (mysql -uroot -e "GRANT ALL PRIVILEGES ON $CHURCHCRM_DATABASE.* TO '$CHURCHCRM_DB_USER'@'localhost';"); then
  echo "Granting all privileges on \"$CHURCHCRM_DATABASE\" to '$CHURCHCRM_DB_USER'@'localhost'"
else
  echo "There was a problem granting privileges on the Database \"$CHURCHCRM_DATABASE\" to '$CHURCHCRM_DB_USER'@'localhost'"
fi

mysql -uroot -e "FLUSH PRIVILEGES;"

echo "[mysqld]" >> /etc/mysql/conf.d/disable_strict_mode.cnf
echo "sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" >> /etc/mysql/conf.d/disable_strict_mode.cnf
service mysql restart

echo "Finished ChurchCRM Database setup successfully"

echo "Setting up ChurchCRM Config file"
cp /var/www/churchcrm/Include/Config.php.example /var/www/churchcrm/Include/Config.php

sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_NAME||/$CHURCHCRM_DATABASE/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_USER||/$CHURCHCRM_DB_USER/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_PASSWORD||/$CHURCHCRM_DB_PASSWORD/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||URL||//g" /var/www/churchcrm/Include/Config.php
sed -i "s/||ROOT_PATH||//g" /var/www/churchcrm/Include/Config.php

echo "Setting up Apache Virtual Host for ChurchCRM"

cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf

sed -i "s/webmaster@localhost/$USER_EMAIL/g" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf
sed -i "s#/var/www/html#/var/www/churchcrm#g" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf
sed -i "/ServerAdmin/a         ServerName $DOMAIN_CHURCHCRM.$DOMAIN_NAME" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf

a2ensite $DOMAIN_CHURCHCRM.$DOMAIN_NAME

service apache2 reload

echo "Successfully installed and Set up ChurchCRM!"
