#!/bin/bash
echo ""
echo "#   Installing Latest ChurchCRM and Dependencies    #"
echo ""

#Getting .env variables
set -o allexport
source ../wb.conf

cd /var/www
#Download Latest Stable release
#curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"
#Download Latest PR
curl -sOL "$(jq -r ".[0] | .assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases" ))"
crmzip=$(find -iname Church*.zip)
unzip $crmzip
rm $crmzip
chown -R www-data:www-data churchcrm
chmod -R 755 churchcrm
find ./churchcrm/. -type f -exec chmod 644 {} +

PKG_NAME=php7.0-mbstring
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

PKG_NAME=php7.0-mcrypt
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $PKG_NAME|grep "install ok installed")
echo Checking for $PKG_NAME: $PKG_OK
if [ "" == "$PKG_OK" ]; then
  echo "No $PKG_NAME. Setting up $PKG_NAME."
  sudo apt --yes install $PKG_NAME
fi

echo ""
echo "#       Creating ChurchCRM User and Database        #"
echo ""

mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $CHURCHCRM_DATABASE;"
echo "Database \"$CHURCHCRM_DATABASE\" created"
mysql -uroot -e "CREATE USER IF NOT EXISTS '$CHURCHCRM_DB_USER'@'localhost' IDENTIFIED BY '$CHURCHCRM_DB_PASSWORD';"
echo "User \"$CHURCHCRM_DB_USER\" created @localhost with password \"$CHURCHCRM_DB_PASSWORD\""
mysql -uroot -e "GRANT ALL PRIVILEGES ON $CHURCHCRM_DATABASE.* TO '$CHURCHCRM_DB_USER'@'localhost';"
echo "Granting all privileges on \"$CHURCHCRM_DATABASE\" to '$CHURCHCRM_DB_USER'@'localhost'"
mysql -uroot -e "FLUSH PRIVILEGES;"

echo "Finished ChurchCRM Database setup successfully"

echo "Setting up ChurchCRM Config file"
cp /var/www/churchcrm/Include/Config.php.example /var/www/churchcrm/Include/Config.php

sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_NAME||/$CHURCHCRM_DATABASE/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_USER||/$CHURCHCRM_DB_USER/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||DB_PASSWORD||/$CHURCHCRM_DB_PASSWORD/g" /var/www/churchcrm/Include/Config.php
sed -i "s/||URL||//g" /var/www/churchcrm/Include/Config.php
sed -i "s/||ROOT_PATH||//g" /var/www/churchcrm/Include/Config.php

echo "Setting up Apache Virtual Host for ChurchCRM"

cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf

sed -i "s/webmaster@localhost/$USER_EMAIL/g" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf
sed -i "s#/var/www/html#/var/www/churchcrm#g" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf
sed -i "/ServerAdmin/a         ServerName $DOMAIN_CHURCHCRM.$DOMAIN_NAME" /etc/apache2/sites-available/$DOMAIN_CHURCHCRM.$DOMAIN_NAME.conf

a2ensite $DOMAIN_CHURCHCRM.$DOMAIN_NAME

service apache2 reload

echo "Successfully installed and Set up ChurchCRM!"
