#!/bin/bash

echo ""
echo "#   Moving OwnCloud Files to Attached Volume    #"
echo ""

#Getting .env variables
if [ ! $DOMAIN_NAME ]; then
  PWDIR=${PWD##*/}
  set -o allexport
  if [ $PWDIR == "webbuild-setup" ]; then
    source ./wb.conf
  elif [ $PWDIR == "install-files" ]; then
    source ../wb.conf
  fi
fi

echo -e "Stopping Apache server to move your Owncloud Data"
systemctl stop apache2

VOLUME_NAME=$(ls /dev/disk/by-id | awk -F 'DO_Volume_' '{print $2}')
export VOLUME_NAME

echo -e "Moving your Data to /mnt/owncloud"
mv /var/www/owncloud/data /mnt/$VOLUME_NAME/owncloud/

echo -e "Changing your configuration..."
sed -i "s#/var/www/owncloud/data#/mnt/$VOLUME_NAME/owncloud/data#g" /var/www/owncloud/config/config.example.php

echo -e "Starting Apache Server again"
systemctl start apache2

echo -e "I have successfully moved your data to the Volume!"
