#!/bin/bash
# This is to download and install the latest Skipper plugins from github

PLUGINDIR="/var/www/html/web/app/plugins"

SKIPPER_PLUGINS="skipper-addons"

for i in $SKIPPER_PLUGINS; do
  if [ -d $PLUGINDIR/$i ]; then
    rm -R $PLUGINDIR/$i
    echo -e "----------------------------"
    echo -e "Updating the $i plugin"
    echo -e "----------------------------"
    wait
  else
    echo -e "----------------------------"
    echo -e "Installing the $i plugin"
    echo -e "----------------------------"
  fi
  git clone https://github.com/jaskipper/$i.git $PLUGINDIR/$i
  chown -R www-data:www-data $PLUGINDIR/$i
done
