#!/bin/bash

echo "#####################################################"
echo "#                    Setting up SSL                 #"
echo "#####################################################"

#Getting .env variables
if [ ! $DOMAIN_NAME ]; then
  PWDIR=${PWD##*/}
  set -o allexport
  if [ $PWDIR == "webbuild-setup" ]; then
    source ./wb.conf
  elif [ $PWDIR == "install-files" ]; then
    source ../wb.conf
  fi
fi

apt --yes update
echo -e "First let's install the LetsEncrypt Installer"
apt --yes install python-letsencrypt-apache

if ping -c 1 $DOMAIN_NAME &> /dev/null
then
  DOMAIN_NAME_ENCRYPT="-d $DOMAIN_NAME"
fi

if ping -c 1 "www.$DOMAIN_NAME" &> /dev/null
then
  DOMAIN_WWW_ENCRYPT="-d www.$DOMAIN_NAME"
fi

# CHANGING THIS AROUND SO THAT IF WP IS A SUBDOMAIN, WE WILL MAKE CHURCHCRM AND OWNCLOUD SUBDOMAINS OF THE TOP DOMAIN
if [ $WP_SUBDOMAIN = "yes" ]; then
  TOP_DOMAIN = ${DOMAIN_NAME#*.};
else
  TOP_DOMAIN = $DOMAIN_NAME;
fi

if [ $CHURCHCRM_INSTALL=yes ]
then
  if ping -c 1 $DOMAIN_CHURCHCRM.$TOP_DOMAIN &> /dev/null
  then
    DOMAIN_CHURCHCRM_ENCRYPT="-d $DOMAIN_CHURCHCRM.$TOP_DOMAIN"
  else
    echo "COULD NOT CONNECT TO $DOMAIN_CHURCHCRM.$TOP_DOMAIN. Stopping install of SSL Certificates."
    echo "Be sure to have your Networking settings in Digital Ocean set up right and then re-run the"
    echo "sslsetup script like this while in the project folder: ./sslsetup"
    SSLHALT=1
  fi
fi

if [ $OWNCLOUD_INSTALL=yes ]
then
  if ping -c 1 $DOMAIN_OWNCLOUD.$TOP_DOMAIN &> /dev/null
  then
    DOMAIN_OWNCLOUD_ENCRYPT="-d $DOMAIN_OWNCLOUD.$TOP_DOMAIN"
  else
    echo "COULD NOT CONNECT TO $DOMAIN_OWNCLOUD.$TOP_DOMAIN. Stopping install of SSL Certificates."
    echo "Be sure to have your Networking settings in Digital Ocean set up right and then re-run the"
    echo "sslsetup script like this while in the project folder: ./sslsetup"
    SSLHALT=1
  fi
fi

letsencrypt --apache $DOMAIN_NAME_ENCRYPT $DOMAIN_WWW_ENCRYPT $DOMAIN_CHURCHCRM_ENCRYPT $DOMAIN_OWNCLOUD_ENCRYPT

echo "30 2 * * 1 /usr/bin/letsencrypt renew >> /var/log/le-renew.log" >> /var/spool/cron/crontabs/root
chmod 600 /var/spool/cron/crontabs/root

sed -i "/<\/Directory>/a <IfModule mod_headers.c>" /etc/apache2/sites-available/$DOMAIN_OWNCLOUD.$TOP_DOMAIN-le-ssl.conf
sed -i "/<IfModule mod_headers.c>/a Header always set Strict-Transport-Security \"max-age=15552000; includeSubDomains\"" /etc/apache2/sites-available/$DOMAIN_OWNCLOUD.$TOP_DOMAIN-le-ssl.conf
sed -i "/max-age=15552000;/a <\/IfModule>" /etc/apache2/sites-available/$DOMAIN_OWNCLOUD.$TOP_DOMAIN-le-ssl.conf


service apache2 reload
