#!/bin/bash

echo "#####################################################"
echo "#                    Setting up SSL                 #"
echo "#####################################################"

apt --yes install python-letsencrypt-apache

if ping -c 1 $DOMAIN_NAME &> /dev/null
then
  DOMAIN_NAME_ENCRYPT="-d $DOMAIN_NAME"
fi

if ping -c 1 "www.$DOMAIN_NAME" &> /dev/null
then
  DOMAIN_WWW_ENCRYPT="-d www.$DOMAIN_NAME"
fi

if $CHURCHCRM_INSTALL="yes"
then
  if ping -c 1 $DOMAIN_CHURCHCRM.$DOMAIN_NAME &> /dev/null
  then
    DOMAIN_CHURCHCRM_ENCRYPT="-d $DOMAIN_CHURCHCRM.$DOMAIN_NAME"
  else
    echo "COULD NOT CONNECT TO $DOMAIN_CHURCHCRM.$DOMAIN_NAME. Stopping install of SSL Certificates."
    echo "Be sure to have your Networking settings in Digital Ocean set up right and then re-run the"
    echo "sslsetup script like this while in the project folder: ./sslsetup"
    SSLHALT=1
  fi
fi

if $OWNCLOUD_INSTALL="yes"
then
  if ping -c 1 $DOMAIN_OWNCLOUD.$DOMAIN_NAME &> /dev/null
  then
    DOMAIN_OWNCLOUD_ENCRYPT="-d $DOMAIN_OWNCLOUD.$DOMAIN_NAME"
  else
    echo "COULD NOT CONNECT TO $DOMAIN_OWNCLOUD.$DOMAIN_NAME. Stopping install of SSL Certificates."
    echo "Be sure to have your Networking settings in Digital Ocean set up right and then re-run the"
    echo "sslsetup script like this while in the project folder: ./sslsetup"
    SSLHALT=1
  fi
fi

if [ ! $SSLHALT=1 ]
then
  letsencrypt --apache $DOMAIN_NAME_ENCRYPT $DOMAIN_WWW_ENCRYPT $DOMAIN_CHURCHCRM_ENCRYPT $DOMAIN_OWNCLOUD_ENCRYPT
fi

echo "30 2 * * 1 /usr/local/sbin/certbot-auto renew >> /var/log/le-renew.log" >> /var/spool/cron/crontabs/root
chmod 600 /var/spool/cron/crontabs/root

service apache2 reload

echo "Successfully installed and Set up your SSL Certificates!"
